#Headless Service for StatefulSets
apiVersion: v1
kind: Service
metadata:
  namespace: mongodemo
  name: mongo-db
  labels:
    name: mongo-db
spec:
 ports:
 - port: 27017
   targetPort: 27017
 clusterIP: None
 selector:
   app: mongo