apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wordpressdemo
  labels:
    app: wordpress
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None